name: Push to Hugging Face Space

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Push to Hugging Face
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git remote add hf https://username:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/yukee1992/AutoVideo
        git push hf main --force
